name: DiscoSheep
main: gibstick.bukkit.discosheep.DiscoSheep
authors: [Gibstick, RangerMauve]
version: 1.0.1
commands:
  ds:
    description: "Main DiscoSheep command"
    usage: |
        <command> <subcommand> [arguments]
        Use /ds help for more information
        To stop your party, use /ds stop.
permissions:
  discosheep.*:
    description: Permission node for all DiscoSheep commands
    default: op
    children:
      discosheep.party: true
      discosheep.partyall: true
      discosheep.fireworks: true
      discosheep.stopall: true
      discosheep.reload: true
  discosheep.party:
    description: Allows a player to have a party of one
    default: op
  discosheep.partyall:
    description: Allows a player to call a server-wide party
    default: op
  discosheep.stopall:
    description: Allows a player to stop all parties on the server
    default: op
  discosheep.fireworks:
    description: Allows a player to enable have parties with fireworks
    default: op
  discosheep.reload:
    description: Allows a player to reload settings from config.yml
    default: op
  discosheep.other:
    description: Allows a player to call parties for other people, including themselves.
    default: op
    children:
      discosheep.party: true