name: DiscoSheep
main: gibstick.bukkit.discosheep.DiscoSheep
version: 0.9
commands:
  ds:
    description: "Main DiscoSheep command"
    usage: /ds
    permission: discosheep.party
    permission-message: You don't have permission