name: DiscoSheep
main: gibstick.bukkit.DiscoSheep.DiscoSheep
version: 0.7
commands:
  ds:
    description: "Main DiscoSheep command"
    usage: /ds
    permission: discosheep.party
    permission-message: You don't have permission